builds:
  - id: "feederd"
    main: ./cmd/feederd
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: feederd
checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - id: feederd
    format: binary
    builds:
      - feederd
    name_template: "feederd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

dockers:
  # push always either release or prerelease with a docker tag with the semver only
  - skip_push: false
    dockerfile: Dockerfile
    # image templates
    image_templates:
      - "ghcr.io/tdex-network/feederd:{{ .Tag }}"
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - cmd
  # push only release with both a docker tag latest and one with the semver
  - skip_push: auto
    dockerfile: Dockerfile
    # image templates
    image_templates:
      - "ghcr.io/tdex-network/feederd:latest"
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"
    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd